PersistantData = {
	StrikeGroups = {},
	Squadrons = {
		{
			type = "Vgr_ResourceCollector",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 6,
		},
		{
			type = "vgr_carrier",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 1,
		},
		{
			type = "vgr_resourcecontroller",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 1,
		},
		{
			type = "vgr_battlecruiser",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 2,
		},
		{
			type = "vgr_assaultfrigate",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 5,
		},
		{
			type = "vgr_drone",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 5,
		},
		{
			type = "vgr_dreadnaught",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 1,
		},
		{
			type = "vgr_destroyer",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 2,
		},
	},
	Research = {},
}